require('dotenv').config();
const path=require('path'),fs=require('fs'),express=require('express'),cors=require('cors'),helmet=require('helmet'),morgan=require('morgan'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),multer=require('multer'),Stripe=require('stripe');
const{Pool}=require('pg');
const PORT=process.env.PORT||3000,JWT_SECRET=process.env.JWT_SECRET||'dev-secret-change-me',APP_URL=(process.env.APP_URL||'').replace(/\/$/,''),UPLOAD_DIR=process.env.UPLOAD_DIR||'uploads',ABS_UPLOAD_DIR=path.resolve(UPLOAD_DIR),BREVO_API_KEY=process.env.BREVO_API_KEY||'',BREVO_SENDER_EMAIL=process.env.BREVO_SENDER_EMAIL||'',BREVO_SENDER_NAME=process.env.BREVO_SENDER_NAME||'Home Care';
if(!fs.existsSync(ABS_UPLOAD_DIR))fs.mkdirSync(ABS_UPLOAD_DIR,{recursive:true});
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});
const stripe=process.env.STRIPE_SECRET_KEY?new Stripe(process.env.STRIPE_SECRET_KEY):null;
const packageConfig={base:{label:'Base',priceCents:3900,days:30},comfort:{label:'Comfort',priceCents:7900,days:15},premium:{label:'Premium',priceCents:19900,days:7},villa_giardino:{label:'Villa & Giardino',priceCents:30000,days:7,from:true},localita_limitrofe:{label:'Località Limitrofe',priceCents:15000,days:30,from:true}};
const CHECKLISTS={base:['Verifica visiva accessi, porte e finestre','Verifica della presenza di eventuali segni visibili di infiltrazioni o umidità','Report fotografico'],comfort:['Verifica visiva accessi, porte e finestre','Aerazione ambienti','Verifica visiva delle parti accessibili degli impianti e segnalazione di eventuali anomalie riscontrabili','Ritiro posta o piccole consegne','Report fotografico'],premium:['Controllo settimanale dell’immobile','Preparazione della casa prima dell’arrivo del cliente, con almeno 15 giorni di preavviso','Verifiche periodiche approfondite','Report fotografico dettagliato','Priorità nella pianificazione degli interventi'],villa_giardino:['Controllo settimanale dell’immobile','Verifica generale dello stato della proprietà e delle aree esterne','Cura ordinaria giardino e spazi esterni','Irrigazione se prevista o concordata','Verifica visiva di cancelli, recinzioni e illuminazione esterna','Report fotografico dettagliato'],localita_limitrofe:['Servizio dedicato agli immobili fuori dal comune di Badesi','Frequenza e attività definite in base alla distanza e ai servizi richiesti','Report fotografico']};
const q=(sql,p=[])=>pool.query(sql,p),cents=v=>{const n=Number(String(v||'').replace(',','.'));return Number.isFinite(n)&&n>0?Math.round(n*100):null},valid=a=>`(${a}.payment_status='paid' AND (${a}.paid_until IS NULL OR ${a}.paid_until>=CURRENT_DATE))`,next=(t)=>{const d=new Date();d.setDate(d.getDate()+(packageConfig[t]||packageConfig.base).days);return d.toISOString().slice(0,10)},token=u=>jwt.sign({id:u.id,role:u.role,customerId:u.customer_id||null},JWT_SECRET,{expiresIn:'14d'});
async function userById(id){return(await q('SELECT id,name,email,phone,role,customer_id,email_confirmed FROM users WHERE id=$1',[id])).rows[0]||null}
function auth(){return async(req,res,next)=>{try{const h=req.headers.authorization||'',t=h.startsWith('Bearer ')?h.slice(7):null;if(!t)return res.status(401).json({error:'Accesso richiesto'});const u=await userById(jwt.verify(t,JWT_SECRET).id);if(!u)return res.status(401).json({error:'Utente non trovato'});req.user=u;next()}catch(e){res.status(401).json({error:'Sessione non valida'})}}}
const admin=(req,res,next)=>req.user?.role==='admin'?next():res.status(403).json({error:'Solo admin'}),staff=(req,res,next)=>['admin','helper'].includes(req.user?.role)?next():res.status(403).json({error:'Solo staff'}),client=(req,res,next)=>req.user?.role==='client'?next():res.status(403).json({error:'Solo cliente'});
function dist(a,b,c,d){const r=x=>Number(x)*Math.PI/180,R=6371,dl=r(c-a),dn=r(d-b),x=Math.sin(dl/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(dn/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function order(lat,lng,rows){let rest=rows.filter(p=>p.latitude&&p.longitude).map(p=>({...p})),out=[],cl=+lat,cn=+lng,total=0;while(rest.length){let bi=0,bd=1e9;rest.forEach((p,i)=>{const dd=dist(cl,cn,+p.latitude,+p.longitude);if(dd<bd){bd=dd;bi=i}});const[p]=rest.splice(bi,1);p.distance_from_previous_km=+bd.toFixed(2);total+=bd;out.push(p);cl=+p.latitude;cn=+p.longitude}return{ordered:out,totalKm:+total.toFixed(2)}}
async function brevo(to,subject,html){if(!BREVO_API_KEY||!BREVO_SENDER_EMAIL)return{sent:false};const r=await fetch('https://api.brevo.com/v3/smtp/email',{method:'POST',headers:{'api-key':BREVO_API_KEY,'Content-Type':'application/json',accept:'application/json'},body:JSON.stringify({sender:{name:BREVO_SENDER_NAME,email:BREVO_SENDER_EMAIL},to:[{email:to}],subject,htmlContent:html})});return{sent:r.ok}}
const baseUrl=req=>APP_URL||`${req.protocol}://${req.get('host')}`,code=()=>`${Date.now()}-${Math.random().toString(36).slice(2)}${Math.random().toString(36).slice(2)}`;
function hide(rows,req){if(req.user?.role!=='helper')return rows;return rows.map(r=>{const x={...r};['payment_status','paid_until','manual_payment_note','last_manual_payment_at','stripe_customer_id','stripe_subscription_id','monthly_price_cents','customer_email'].forEach(k=>delete x[k]);return x})}
const app=express();app.set('trust proxy',1);app.use(helmet({contentSecurityPolicy:false}),cors(),morgan('tiny'));
app.post('/api/stripe/webhook',express.raw({type:'application/json'}),async(req,res)=>{if(!stripe)return res.json({received:true,disabled:true});let ev;try{ev=process.env.STRIPE_WEBHOOK_SECRET?stripe.webhooks.constructEvent(req.body,req.headers['stripe-signature'],process.env.STRIPE_WEBHOOK_SECRET):JSON.parse(req.body.toString())}catch(e){return res.status(400).send(e.message)}try{if(ev.type==='checkout.session.completed'){const s=ev.data.object;if(s.metadata?.kind==='extra_payment')await q("UPDATE extra_payments SET status='paid',paid_at=NOW(),updated_at=NOW() WHERE id=$1",[s.metadata.extraPaymentId]);if(s.metadata?.kind==='subscription')await q("UPDATE customers SET payment_status='paid',paid_until=NULL,stripe_customer_id=COALESCE(stripe_customer_id,$2),stripe_subscription_id=COALESCE(stripe_subscription_id,$3),updated_at=NOW() WHERE id=$1",[s.metadata.customerId,s.customer,s.subscription])}if(ev.type==='invoice.payment_failed'&&ev.data.object.customer)await q("UPDATE customers SET payment_status='past_due' WHERE stripe_customer_id=$1",[ev.data.object.customer]);res.json({received:true})}catch(e){console.error(e);res.status(500).json({error:'Errore webhook'})}});
app.use(express.json({limit:'10mb'}),express.urlencoded({extended:true}),'/uploads',express.static(ABS_UPLOAD_DIR),express.static(path.join(__dirname,'public')));
const upload=multer({storage:multer.diskStorage({destination:(r,f,cb)=>cb(null,ABS_UPLOAD_DIR),filename:(r,f,cb)=>cb(null,`${Date.now()}-${Math.round(Math.random()*1e9)}${path.extname(f.originalname||'.jpg')}`)}),limits:{fileSize:12*1024*1024,files:12}});
app.get('/api/health',(req,res)=>res.json({ok:true,app:'home-care-pwa'}));
app.get('/api/config',(req,res)=>res.json({packages:packageConfig,checklists:CHECKLISTS,stripeEnabled:!!stripe,brevoEnabled:!!(BREVO_API_KEY&&BREVO_SENDER_EMAIL)}));
app.post('/api/auth/register',async(req,res)=>{const{name,email,phone,password}=req.body;if(!name||!email||!password)return res.status(400).json({error:'Nome, email e password obbligatori'});if(String(password).length<8)return res.status(400).json({error:'La password deve contenere almeno 8 caratteri'});const db=await pool.connect();try{await db.query('BEGIN');const mail=String(email).toLowerCase().trim();if((await db.query('SELECT id FROM users WHERE LOWER(email)=LOWER($1)',[mail])).rows[0]){await db.query('ROLLBACK');return res.status(409).json({error:'Email già registrata'})}const cu=(await db.query("INSERT INTO customers(name,email,phone,payment_status) VALUES($1,$2,$3,'unpaid') RETURNING *",[name,mail,phone||null])).rows[0],hash=await bcrypt.hash(password,12),confirm=code(),expires=new Date(Date.now()+48*60*60*1000);await db.query("INSERT INTO users(name,email,phone,password_hash,role,customer_id,email_confirmed,email_confirm_code,email_confirm_expires_at) VALUES($1,$2,$3,$4,'client',$5,FALSE,$6,$7)",[name,mail,phone||null,hash,cu.id,confirm,expires]);await db.query('COMMIT');const url=`${baseUrl(req).replace(/\/$/,'')}/api/auth/confirm-email?code=${encodeURIComponent(confirm)}`,sent=await brevo(mail,'Conferma email - Home Care',`<p>Ciao ${name}, conferma la tua email cliccando qui:</p><p><a href="${url}">Conferma email</a></p>`);res.status(201).json({message:sent.sent?'Registrazione completata. Controlla la tua email.':'Registrazione completata. Brevo non configurato: usa il link di test.',emailSent:sent.sent,confirmationUrl:sent.sent?undefined:url})}catch(e){await db.query('ROLLBACK').catch(()=>null);console.error(e);res.status(500).json({error:'Errore registrazione'})}finally{db.release()}});
app.get('/api/auth/confirm-email',async(req,res)=>{const r=await q("UPDATE users SET email_confirmed=TRUE,email_confirm_code=NULL,email_confirm_expires_at=NULL,updated_at=NOW() WHERE email_confirm_code=$1 AND email_confirm_expires_at>NOW() RETURNING email",[String(req.query.code||'')]);res.status(r.rows[0]?200:400).send(r.rows[0]?'<h1>Email confermata</h1><p><a href="/">Vai al login</a></p>':'<h1>Link non valido o scaduto</h1>')});
app.post('/api/auth/login',async(req,res)=>{const{email,password}=req.body;if(!email||!password)return res.status(400).json({error:'Email e password obbligatorie'});const u=(await q('SELECT * FROM users WHERE LOWER(email)=LOWER($1)',[email])).rows[0];if(!u||!await bcrypt.compare(password,u.password_hash))return res.status(401).json({error:'Credenziali non valide'});if(u.role==='client'&&!u.email_confirmed)return res.status(403).json({error:'Email non confermata. Controlla la tua casella email.'});res.json({token:token(u),user:{id:u.id,name:u.name,email:u.email,role:u.role,customerId:u.customer_id}})});
app.get('/api/auth/me',auth(),(req,res)=>res.json({user:req.user}));
app.get('/api/admin/summary',auth(),staff,async(req,res)=>{const v=valid('c'),[c,p,d,b,t,e]=await Promise.all([q('SELECT COUNT(*)::int count FROM customers'),q('SELECT COUNT(*)::int count FROM properties WHERE active=TRUE'),q(`SELECT COUNT(*)::int count FROM properties p JOIN customers c ON c.id=p.customer_id WHERE p.active=TRUE AND p.next_check_date<=CURRENT_DATE AND ${v}`),q(`SELECT COUNT(*)::int count FROM properties p JOIN customers c ON c.id=p.customer_id WHERE p.active=TRUE AND p.next_check_date<=CURRENT_DATE AND NOT ${v}`),q("SELECT COUNT(*)::int count FROM tasks WHERE status='todo' AND due_date<=CURRENT_DATE"),req.user.role==='admin'?q("SELECT COUNT(*)::int count FROM extra_payments WHERE status='pending'"):Promise.resolve({rows:[{count:0}]})]);res.json({customers:c.rows[0].count,properties:p.rows[0].count,dueChecks:d.rows[0].count,blockedChecks:b.rows[0].count,todoTasks:t.rows[0].count,pendingExtraPayments:e.rows[0].count})});
app.get('/api/admin/helpers',auth(),admin,async(req,res)=>res.json({helpers:(await q("SELECT id,name,email,phone,role,email_confirmed,created_at FROM users WHERE role='helper' ORDER BY created_at DESC")).rows}));
app.post('/api/admin/helpers',auth(),admin,async(req,res)=>{const{name,email,phone,password}=req.body;if(!name||!email||!password)return res.status(400).json({error:'Nome, email e password obbligatori'});const hash=await bcrypt.hash(password,12);res.status(201).json({helper:(await q("INSERT INTO users(name,email,phone,password_hash,role,email_confirmed) VALUES($1,LOWER($2),$3,$4,'helper',TRUE) RETURNING id,name,email,phone,role,email_confirmed",[name,email,phone||null,hash])).rows[0]})});
app.get('/api/admin/customers',auth(),staff,async(req,res)=>{const rows=(await q(`SELECT c.*,COUNT(p.id)::int properties_count,CASE WHEN ${valid('c')} THEN TRUE ELSE FALSE END payment_valid FROM customers c LEFT JOIN properties p ON p.customer_id=c.id GROUP BY c.id ORDER BY c.created_at DESC`)).rows;res.json({customers:hide(rows,req)})});
app.post('/api/admin/customers',auth(),admin,async(req,res)=>{const{name,email,phone,notes,payment_status='unpaid',paid_until=null}=req.body;if(!name)return res.status(400).json({error:'Nome cliente obbligatorio'});res.status(201).json({customer:(await q('INSERT INTO customers(name,email,phone,notes,payment_status,paid_until) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[name,email||null,phone||null,notes||null,payment_status,paid_until])).rows[0]})});
app.post('/api/admin/customers/:id/manual-payment',auth(),admin,async(req,res)=>{const{amount_euro,paid_until,method='contanti',description='Pagamento manuale'}=req.body;if(!paid_until)return res.status(400).json({error:'Indica la data pagato fino al'});const amount=amount_euro?cents(amount_euro):null;await q('INSERT INTO manual_payments(customer_id,amount_cents,method,description,paid_until) VALUES($1,$2,$3,$4,$5)',[req.params.id,amount,method,description,paid_until]);res.json({customer:(await q("UPDATE customers SET payment_status='paid',paid_until=$2,manual_payment_note=$3,last_manual_payment_at=NOW(),updated_at=NOW() WHERE id=$1 RETURNING *",[req.params.id,paid_until,`${method}${amount?' - €'+(amount/100).toFixed(2):''} - ${description}`])).rows[0]})});
app.get('/api/admin/properties',auth(),staff,async(req,res)=>{const rows=(await q(`SELECT p.*,c.name customer_name,c.email customer_email,c.phone customer_phone,c.payment_status,c.paid_until,CASE WHEN ${valid('c')} THEN TRUE ELSE FALSE END payment_valid FROM properties p JOIN customers c ON c.id=p.customer_id ORDER BY p.created_at DESC`)).rows;res.json({properties:hide(rows,req)})});
app.post('/api/admin/properties',auth(),admin,async(req,res)=>{const{customer_id,name,address,city,zone,package_type='base',notes,latitude,longitude}=req.body;if(!customer_id||!name)return res.status(400).json({error:'Cliente e nome immobile obbligatori'});const cfg=packageConfig[package_type]||packageConfig.base;res.status(201).json({property:(await q('INSERT INTO properties(customer_id,name,address,city,zone,package_type,monthly_price_cents,next_check_date,notes,latitude,longitude) VALUES($1,$2,$3,$4,$5,$6,$7,CURRENT_DATE,$8,$9,$10) RETURNING *',[customer_id,name,address||null,city||'Badesi',zone||null,package_type,cfg.priceCents,notes||null,latitude||null,longitude||null])).rows[0]})});
app.post('/api/admin/properties/:id/location',auth(),staff,async(req,res)=>{const{latitude,longitude}=req.body;if(!latitude||!longitude)return res.status(400).json({error:'Coordinate mancanti'});res.json({property:(await q('UPDATE properties SET latitude=$2,longitude=$3,updated_at=NOW() WHERE id=$1 RETURNING *',[req.params.id,latitude,longitude])).rows[0]})});
app.get('/api/admin/due-checks',auth(),staff,async(req,res)=>{const rows=(await q(`SELECT p.*,c.name customer_name,c.phone customer_phone,c.email customer_email,c.payment_status,c.paid_until,CASE WHEN ${valid('c')} THEN FALSE ELSE TRUE END blocked FROM properties p JOIN customers c ON c.id=p.customer_id WHERE p.active=TRUE AND p.next_check_date<=CURRENT_DATE ORDER BY blocked,p.next_check_date,c.name`)).rows;res.json({checks:hide(rows,req)})});
app.post('/api/admin/checks/complete',auth(),staff,upload.array('photos',12),async(req,res)=>{const{property_id,notes,checklist_json}=req.body;if(!property_id)return res.status(400).json({error:'Immobile obbligatorio'});const p=(await q(`SELECT p.*,${valid('c')} payment_valid FROM properties p JOIN customers c ON c.id=p.customer_id WHERE p.id=$1`,[property_id])).rows[0];if(!p)return res.status(404).json({error:'Immobile non trovato'});if(!p.payment_valid)return res.status(402).json({error:'Pagamento non regolare: controllo sospeso'});const photos=(req.files||[]).map(f=>`/uploads/${f.filename}`),r=(await q("INSERT INTO checks(property_id,due_date,completed_at,status,notes,checklist_json,photo_urls) VALUES($1,CURRENT_DATE,NOW(),'done',$2,$3::jsonb,$4::jsonb) RETURNING *",[property_id,notes||null,checklist_json||'[]',JSON.stringify(photos)])).rows[0];await q('UPDATE properties SET next_check_date=$2,updated_at=NOW() WHERE id=$1',[property_id,next(p.package_type)]);res.status(201).json({check:r})});
app.get('/api/admin/tasks',auth(),staff,async(req,res)=>res.json({tasks:(await q("SELECT t.*,c.name customer_name,p.name property_name,p.address FROM tasks t LEFT JOIN customers c ON c.id=t.customer_id LEFT JOIN properties p ON p.id=t.property_id WHERE t.status=$1 ORDER BY t.due_date,t.priority DESC",[req.query.status||'todo'])).rows}));
app.post('/api/admin/tasks',auth(),staff,async(req,res)=>{const{title,description,type='controllo',priority='normale',due_date,customer_id,property_id}=req.body;if(!title)return res.status(400).json({error:'Titolo obbligatorio'});res.status(201).json({task:(await q('INSERT INTO tasks(title,description,type,priority,due_date,customer_id,property_id) VALUES($1,$2,$3,$4,COALESCE($5,CURRENT_DATE),$6,$7) RETURNING *',[title,description||null,type,priority,due_date||null,customer_id||null,property_id||null])).rows[0]})});
app.post('/api/admin/tasks/:id/done',auth(),staff,async(req,res)=>res.json({task:(await q("UPDATE tasks SET status='done',completed_at=NOW(),updated_at=NOW() WHERE id=$1 RETURNING *",[req.params.id])).rows[0]}));
app.get('/api/admin/route-plan',auth(),staff,async(req,res)=>{const lat=Number(req.query.lat||40.9663),lng=Number(req.query.lng||8.8814),where=["p.active=TRUE","p.latitude IS NOT NULL","p.longitude IS NOT NULL",valid('c')];if(req.query.onlyDue!=='0')where.push('p.next_check_date<=CURRENT_DATE');const rows=hide((await q(`SELECT p.*,c.name customer_name,c.phone customer_phone,c.payment_status,c.paid_until FROM properties p JOIN customers c ON c.id=p.customer_id WHERE ${where.join(' AND ')}`)).rows,req);const r=order(lat,lng,rows);res.json({origin:{lat,lng},totalKm:r.totalKm,properties:r.ordered})});
app.get('/api/admin/extra-payments',auth(),admin,async(req,res)=>res.json({payments:(await q('SELECT e.*,c.name customer_name,c.email customer_email,c.phone customer_phone FROM extra_payments e JOIN customers c ON c.id=e.customer_id ORDER BY e.created_at DESC')).rows}));
app.post('/api/admin/extra-payments',auth(),admin,async(req,res)=>{const{customer_id,amount_euro,description}=req.body,amount=cents(amount_euro);if(!customer_id||!amount||!description)return res.status(400).json({error:'Cliente, importo e descrizione obbligatori'});let extra=(await q('INSERT INTO extra_payments(customer_id,amount_cents,description) VALUES($1,$2,$3) RETURNING *',[customer_id,amount,description])).rows[0];if(!stripe)return res.status(201).json({payment:extra,stripeDisabled:true});res.status(201).json({payment:extra})});
app.get('/api/admin/manual-payments',auth(),admin,async(req,res)=>res.json({payments:(await q('SELECT m.*,c.name customer_name FROM manual_payments m JOIN customers c ON c.id=m.customer_id ORDER BY m.created_at DESC LIMIT 100')).rows}));
app.get('/api/client/dashboard',auth(),client,async(req,res)=>{const id=req.user.customer_id;const customer=(await q(`SELECT *,CASE WHEN ${valid('customers')} THEN TRUE ELSE FALSE END payment_valid FROM customers WHERE id=$1`,[id])).rows[0],properties=(await q('SELECT * FROM properties WHERE customer_id=$1 AND active=TRUE ORDER BY created_at DESC',[id])).rows,reports=(await q("SELECT ch.*,p.name property_name FROM checks ch JOIN properties p ON p.id=ch.property_id WHERE p.customer_id=$1 AND ch.status='done' ORDER BY ch.completed_at DESC LIMIT 30",[id])).rows,payments=(await q('SELECT * FROM extra_payments WHERE customer_id=$1 ORDER BY created_at DESC',[id])).rows;res.json({customer,properties,reports,payments,packages:packageConfig})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'Errore interno del server'})});app.listen(PORT,()=>console.log(`Home Care PWA avviata sulla porta ${PORT}`));
