ALTER TABLE users ADD COLUMN IF NOT EXISTS email_confirmed BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_confirm_code TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_confirm_expires_at TIMESTAMPTZ;
