const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const source = path.join(root, 'server3.js');
const target = path.join(root, '.runtime-server-v4.js');
let code = fs.readFileSync(source, 'utf8');

function replaceRegex(regex, replacement, label) {
  if (!regex.test(code)) console.warn('Patch non trovato:', label);
  code = code.replace(regex, replacement);
}
function insertAfter(marker, addition, label) {
  if (!code.includes(marker)) console.warn('Patch non trovato:', label);
  else code = code.replace(marker, marker + addition);
}

const helperBlock = `
async function addNotification({audience,customerId=null,title,body,link='/'}){return (await q('INSERT INTO notifications(audience,customer_id,title,body,link) VALUES($1,$2,$3,$4,$5) RETURNING *',[audience,customerId,title,body,link])).rows[0]}
function emailCard(title,body,cta='Apri Home Care',link='/'){const url=(APP_URL||'')+link;return '<div style="margin:0;padding:0;background:#f5f1e8;font-family:Arial,sans-serif;color:#06243a"><div style="max-width:620px;margin:0 auto;padding:30px"><div style="background:#fffdf7;border:1px solid #e1d6c8;border-radius:24px;padding:32px;text-align:center"><div style="font-size:30px;font-weight:800">Home <span style="color:#c7952d">Care</span></div><h1>'+title+'</h1><p style="font-size:16px;line-height:1.6;color:#334155">'+body+'</p><a href="'+url+'" style="display:inline-block;background:#06243a;color:white;text-decoration:none;padding:14px 22px;border-radius:14px;font-weight:800;margin-top:16px">'+cta+'</a></div></div></div>'}
async function notifyCustomer(customerId,title,body,link='/'){await addNotification({audience:'client',customerId,title,body,link});const c=(await q('SELECT email FROM customers WHERE id=$1',[customerId])).rows[0];if(c&&c.email)await brevo(c.email,title,emailCard(title,body,'Apri Home Care',link))}
async function notifyAdmins(title,body,link='/'){await addNotification({audience:'admin',title,body,link});const admins=(await q("SELECT email FROM users WHERE role='admin'")).rows;await Promise.all(admins.map(a=>brevo(a.email,title,emailCard(title,body,'Apri Home Care',link))))}
`;
insertAfter("app.get('/api/config',(req,res)=>res.json({packages:packageConfig,checklists:CHECKLISTS,stripeEnabled:!!stripe,brevoEnabled:!!(BREVO_API_KEY&&BREVO_SENDER_EMAIL)}));", helperBlock + `
app.get('/api/notifications',auth(),async(req,res)=>{const rows=req.user.role==='client'?(await q("SELECT * FROM notifications WHERE audience='client' AND customer_id=$1 ORDER BY created_at DESC LIMIT 80",[req.user.customer_id])).rows:(await q("SELECT * FROM notifications WHERE audience='admin' ORDER BY created_at DESC LIMIT 80")).rows;res.json({notifications:rows,unread:rows.filter(n=>!n.read_at).length})});
app.post('/api/notifications/read',auth(),async(req,res)=>{if(req.user.role==='client')await q("UPDATE notifications SET read_at=NOW() WHERE audience='client' AND customer_id=$1 AND read_at IS NULL",[req.user.customer_id]);else await q("UPDATE notifications SET read_at=NOW() WHERE audience='admin' AND read_at IS NULL");res.json({ok:true})});
`, 'notifications');

replaceRegex(/app\.post\('\/api\/stripe\/webhook'[\s\S]*?app\.use\(express\.json/, `app.post('/api/stripe/webhook',express.raw({type:'application/json'}),async(req,res)=>{if(!stripe)return res.json({received:true,disabled:true});let ev;try{ev=process.env.STRIPE_WEBHOOK_SECRET?stripe.webhooks.constructEvent(req.body,req.headers['stripe-signature'],process.env.STRIPE_WEBHOOK_SECRET):JSON.parse(req.body.toString())}catch(e){return res.status(400).send('Webhook Error: '+e.message)}try{if(ev.type==='checkout.session.completed'){const s=ev.data.object;if(s.metadata&&s.metadata.kind==='extra_payment'){const extra=(await q("UPDATE extra_payments SET status='paid',paid_at=NOW(),updated_at=NOW() WHERE id=$1 RETURNING *",[s.metadata.extraPaymentId])).rows[0];if(extra){await notifyCustomer(extra.customer_id,'Pagamento ricevuto','Il pagamento richiesto è stato ricevuto correttamente.','/?tab=payments');await notifyAdmins('Pagamento extra ricevuto','Un cliente ha saldato un pagamento extra.','/?admin=payments')}}if(s.metadata&&s.metadata.kind==='subscription'&&s.metadata.customerId){await q("UPDATE customers SET payment_status='paid',paid_until=NULL,stripe_customer_id=COALESCE(stripe_customer_id,$2),stripe_subscription_id=COALESCE(stripe_subscription_id,$3),updated_at=NOW() WHERE id=$1",[s.metadata.customerId,s.customer,s.subscription])}}if(ev.type==='checkout.session.expired'){const s=ev.data.object;if(s.metadata&&s.metadata.kind==='extra_payment'){const row=(await q('SELECT * FROM extra_payments WHERE id=$1',[s.metadata.extraPaymentId])).rows[0];if(row)await notifyCustomer(row.customer_id,'Pagamento non completato','Il link di pagamento è scaduto o il pagamento non è stato completato.','/?tab=payments')}}if(ev.type==='invoice.payment_failed'){const inv=ev.data.object;if(inv.customer){const c=(await q("UPDATE customers SET payment_status='past_due',updated_at=NOW() WHERE stripe_customer_id=$1 RETURNING *",[inv.customer])).rows[0];if(c)await notifyCustomer(c.id,'Pagamento non riuscito','Il pagamento del servizio non è andato a buon fine.','/?tab=payments')}}res.json({received:true})}catch(e){console.error(e);res.status(500).json({error:'Errore webhook'})}});
app.use(express.json`, 'stripe webhook');

replaceRegex(/app\.post\('\/api\/admin\/checks\/complete'[\s\S]*?app\.get\('\/api\/admin\/checks'/, `app.post('/api/admin/checks/complete',auth(),staff,upload.array('photos',12),async(req,res)=>{const{property_id,notes,checklist_json}=req.body;if(!property_id)return res.status(400).json({error:'Immobile obbligatorio'});const property=(await q(\`SELECT p.*,c.email customer_email,\${paymentIsValidSql('c')} AS payment_valid FROM properties p JOIN customers c ON c.id=p.customer_id WHERE p.id=$1\`,[property_id])).rows[0];if(!property)return res.status(404).json({error:'Immobile non trovato'});if(!property.payment_valid)return res.status(402).json({error:'Pagamento non regolare: controllo sospeso'});const photoUrls=(req.files||[]).map(file=>\`/uploads/\${file.filename}\`),nextD=nextCheckDate(property.package_type);const check=(await q("INSERT INTO checks (property_id,due_date,completed_at,status,notes,checklist_json,photo_urls) VALUES ($1,CURRENT_DATE,NOW(),'done',$2,$3::jsonb,$4::jsonb) RETURNING *",[property_id,notes||null,checklist_json||'[]',JSON.stringify(photoUrls)])).rows[0];await q('UPDATE properties SET next_check_date=$2,updated_at=NOW() WHERE id=$1',[property_id,nextD]);await notifyCustomer(property.customer_id,'Nuovo report disponibile',\`È disponibile un nuovo report per \${property.name}.\`,'/?tab=reports');res.status(201).json({check,nextCheckDate:nextD})});
app.get('/api/admin/checks'`, 'checks complete');

replaceRegex(/app\.get\('\/api\/admin\/extra-payments'[\s\S]*?app\.get\('\/api\/admin\/manual-payments'/, `async function createExtraCheckout(extraId,req){const row=(await q('SELECT e.*,c.name customer_name,c.email customer_email,c.phone customer_phone,c.stripe_customer_id FROM extra_payments e JOIN customers c ON c.id=e.customer_id WHERE e.id=$1',[extraId])).rows[0];if(!row||!stripe)return row;let scid=row.stripe_customer_id;if(!scid){const sc=await stripe.customers.create({name:row.customer_name,email:row.customer_email||undefined,phone:row.customer_phone||undefined,metadata:{customerId:row.customer_id}});scid=sc.id;await q('UPDATE customers SET stripe_customer_id=$2,updated_at=NOW() WHERE id=$1',[row.customer_id,scid])}const session=await stripe.checkout.sessions.create({customer:scid,mode:'payment',line_items:[{quantity:1,price_data:{currency:'eur',unit_amount:row.amount_cents,product_data:{name:'Home Care - extra / manutenzione',description:row.description}}}],success_url:(APP_URL||baseUrl(req)).replace(/\\/$/,'')+'/?payment=success',cancel_url:(APP_URL||baseUrl(req)).replace(/\\/$/,'')+'/?payment=cancel',expires_at:Math.floor(Date.now()/1000)+7*24*60*60,metadata:{kind:'extra_payment',extraPaymentId:row.id,customerId:row.customer_id}});return (await q('UPDATE extra_payments SET stripe_session_id=$2,payment_url=$3,updated_at=NOW() WHERE id=$1 RETURNING *',[row.id,session.id,session.url])).rows[0]}
app.get('/api/admin/extra-payments',auth(),admin,async(req,res)=>res.json({payments:(await q('SELECT e.*,c.name customer_name,c.email customer_email,c.phone customer_phone FROM extra_payments e JOIN customers c ON c.id=e.customer_id ORDER BY e.created_at DESC')).rows}));
app.post('/api/admin/extra-payments',auth(),admin,async(req,res)=>{const{customer_id,amount_euro,description}=req.body;const amount=toIntCents(amount_euro);if(!customer_id||!amount||!description)return res.status(400).json({error:'Cliente, importo e descrizione obbligatori'});let payment=(await q('INSERT INTO extra_payments(customer_id,amount_cents,description) VALUES($1,$2,$3) RETURNING *',[customer_id,amount,description])).rows[0];payment=await createExtraCheckout(payment.id,req);await notifyCustomer(customer_id,'Nuovo pagamento disponibile',\`Hai un nuovo pagamento/preventivo da saldare: €\${(amount/100).toFixed(2)}.\`,'/?tab=payments');res.status(201).json({payment,stripeDisabled:!stripe})});
app.patch('/api/admin/extra-payments/:id',auth(),admin,async(req,res)=>{const{amount_euro,description}=req.body;const old=(await q('SELECT * FROM extra_payments WHERE id=$1',[req.params.id])).rows[0];if(!old)return res.status(404).json({error:'Pagamento non trovato'});if(old.status==='paid')return res.status(400).json({error:'Non puoi modificare un pagamento già saldato'});const amount=amount_euro?toIntCents(amount_euro):old.amount_cents;let payment=(await q('UPDATE extra_payments SET amount_cents=$2,description=$3,stripe_session_id=NULL,payment_url=NULL,updated_at=NOW() WHERE id=$1 RETURNING *',[req.params.id,amount,description||old.description])).rows[0];payment=await createExtraCheckout(payment.id,req);await notifyCustomer(payment.customer_id,'Pagamento aggiornato','Un pagamento/preventivo è stato aggiornato da Home Care.','/?tab=payments');res.json({payment})});
app.post('/api/admin/extra-payments/:id/cancel',auth(),admin,async(req,res)=>{const row=(await q("UPDATE extra_payments SET status='canceled',payment_url=NULL,updated_at=NOW() WHERE id=$1 AND status<>'paid' RETURNING *",[req.params.id])).rows[0];if(!row)return res.status(404).json({error:'Pagamento non trovato o già saldato'});await notifyCustomer(row.customer_id,'Pagamento annullato','Un pagamento/preventivo è stato annullato da Home Care.','/?tab=payments');res.json({payment:row})});
app.get('/api/admin/manual-payments'`, 'extra payments');

code = code.replace("await q(\"INSERT INTO messages(customer_id,sender_role,sender_name,body,read_by_client,read_by_admin) VALUES($1,'client',$2,$3,TRUE,FALSE)\", [req.user.customer_id, req.user.name || 'Cliente', 'Ho inserito un nuovo immobile da affidare a Home Care: ' + name + ', ' + address]);", "await notifyAdmins('Nuova richiesta immobile', `${req.user.name} ha inserito un nuovo immobile da approvare: ${name}, ${address}`, '/?admin=requests');");
code = code.replace("await q(\"INSERT INTO messages(customer_id,sender_role,sender_name,body,read_by_client,read_by_admin) VALUES($1,'admin','Home Care',$2,FALSE,TRUE)\", [row.customer_id, 'Abbiamo approvato la richiesta per l’immobile: ' + row.name + '.']);", "await notifyCustomer(row.customer_id, 'Immobile approvato', 'La richiesta per il tuo immobile è stata approvata da Home Care.', '/?tab=properties');");
code = code.replace("const row = (await q(\"INSERT INTO messages(customer_id,sender_role,sender_name,body,read_by_client,read_by_admin) VALUES($1,'client',$2,$3,TRUE,FALSE) RETURNING *\", [req.user.customer_id, req.user.name || 'Cliente', body])).rows[0];\n  res.status(201).json({ message: row });", "const row = (await q(\"INSERT INTO messages(customer_id,sender_role,sender_name,body,read_by_client,read_by_admin) VALUES($1,'client',$2,$3,TRUE,FALSE) RETURNING *\", [req.user.customer_id, req.user.name || 'Cliente', body])).rows[0];\n  await notifyAdmins('Nuovo messaggio cliente', `${req.user.name} ha scritto un nuovo messaggio.`, '/?admin=messages');\n  res.status(201).json({ message: row });");
code = code.replace("const row = (await q(\"INSERT INTO messages(customer_id,sender_role,sender_name,body,read_by_client,read_by_admin) VALUES($1,'admin','Home Care',$2,FALSE,TRUE) RETURNING *\", [customer_id, String(body).trim()])).rows[0];\n  res.status(201).json({ message: row });", "const row = (await q(\"INSERT INTO messages(customer_id,sender_role,sender_name,body,read_by_client,read_by_admin) VALUES($1,'admin','Home Care',$2,FALSE,TRUE) RETURNING *\", [customer_id, String(body).trim()])).rows[0];\n  await notifyCustomer(customer_id, 'Nuovo messaggio da Home Care', 'Hai ricevuto un nuovo messaggio nella chat Home Care.', '/?tab=chat');\n  res.status(201).json({ message: row });");

fs.writeFileSync(target, code);
require(target);
